language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
notifications:
    #on_success: change
    on_success: always
    on_failure: always
    irc:
        channels:
            - "irc.perl.org#angel-PS1"
        template:
            - "%{branch}: %{message} %{build_url}"
    email: false
install:
    #- cpanm Dist::Zilla::App::Command::xtest || { cat ~/.cpanm/build.log ; false ; }
    #- dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    #- dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    cpanm Test::More Test::Is Test::Synopsis || { cat ~/.cpanm/build.log ; false ; }
script:
    - prove -lv t
    #- dzil test --author --release
    #- dzil xtest
