language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
notifications:
    #on_success: change
    on_success: always
    on_failure: always
    irc:
        channels:
            - "irc.perl.org#angel-PS1"
        template:
            - "%{branch}: %{message} %{build_url}"
    email: false
install:
    - cpanm --notest Test::More Test::Is Test::Synopsis || { cat ~/.cpanm/build.log ; false ; }
    - test "$TRAVIS_PERL_VERSION" = 5.8 || { cpanm --notest Dist::Milla && dzil listdeps --author --missing | cpanm ; } || { cat ~/.cpanm/build.log ; false ; }
script:
    - prove -lv t
    - test "$TRAVIS_PERL_VERSION" = 5.8 || dzil test --author --release
