language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
# For the container based infrastructure
sudo: false
notifications:
    #on_success: change
    on_success: always
    on_failure: always
    irc:
        channels:
            - "irc.perl.org#angel-PS1"
        template:
            - "%{branch}: %{message} %{build_url}"
    email: false
install:
    - cpanm --notest Test::More Test::Is Test::Synopsis || { cat ~/.cpanm/build.log ; false ; }
    - test "${TRAVIS_PERL_VERSION/./}" -lt 512 || { cpanm --notest Dist::Milla && dzil listdeps --author --missing | cpanm ; } || { cat ~/.cpanm/build.log ; false ; }
script:
    - prove -lv t
    - test "${TRAVIS_PERL_VERSION/./}" -lt 512 || dzil test -v --all --test-verbose
